inherit_mode:
  merge:
    - Exclude

Style/Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/{bundle,setup,rails,rake,spring}'
