default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('ISSUE_TRACKER_API_DATABASE_USERNAME') %>
  password: <%= ENV.fetch('ISSUE_TRACKER_API_DATABASE_PASSWORD') %>
  host:  <%= ENV.fetch('ISSUE_TRACKER_API_DATABASE_HOST') %>

development:
  <<: *default
  database: issue_tracker_api_development

test:
  <<: *default
  database: issue_tracker_api_test

production:
  <<: *default
  database: <%= ENV['ISSUE_TRACKER_API_DATABASE_PRODUCTION'] %>
  password: <%= ENV['ISSUE_TRACKER_API_DATABASE_PASSWORD'] %>
